### ISSUE TITLE
[atom-ide-debugger-node] Error when restarting debugger

### ISSUE THREAD

**Issue by zypA13510** [facebook/nuclide#1618]
### Issue and Steps to Reproduce
The following error message will appear whenever I tried to click the "restart the debugger using the same settings as the current debug session (Ctrl+Shift+F8)" button:
> Failed to start debugger process: Cannot add to an already disposed UniversalDisposable!

(It used to work before, but I'm not sure what breaks it)

### Expected Behavior
The debugger restarts with the same settings.

### Actual Behavior
The debugger throws the error, and display a message
> Process exited (C:\path\index.js (Node))

in the debugger console. Manually clicking the "launch debugger" button afterwards will display a settings panel to start debugging as usual.

### Versions
* Atom: 1.30.0
* Nuclide: Installed via Atom IDE. (atom-ide-debugger-node 0.7.3)
* Client OS: Windows 10 1703 x86-64

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (37)
├── atom-beautify@0.33.1
├── atom-ide-debugger-node@0.7.3
├── atom-ide-ui@0.13.0
├── atom-live-server@2.3.0
├── atom-minify@0.8.0
├── atom-runner@2.7.1
├── autoclose-html@0.23.0
├── autocomplete-modules@2.2.0
├── autocomplete-xml@0.10.1
├── blame@1.0.1
├── build@0.70.0
├── build-grunt@0.4.0
├── busy-signal@1.4.3
├── docblockr@0.13.7
├── editorconfig@2.2.2
├── figlet@0.5.4
├── figletify@0.2.2 (disabled)
├── highlight-selected@0.14.0
├── ide-json@0.2.1
├── ide-yaml@0.4.4
├── intentions@1.1.5
├── linter@2.2.0
├── linter-eslint@8.4.1
├── linter-htmlhint@1.5.1
├── linter-markdown@5.2.2
├── linter-ui-default@1.7.1
├── markdown-writer@2.9.0
├── merge-conflicts@1.4.5
├── minimap@4.29.8
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-linter@2.1.3
├── pigments@0.40.2
├── pinned-tabs@2.1.0
├── simple-drag-drop-text@0.4.0
├── split-diff@1.5.2
└── teletype@0.13.3 (disabled)
```

**Comment by ebluestein** [comment]
This should be working in the most recent Nuclide.

**Comment by zypA13510** [comment]
I'm sorry, but I checked my Atom for package updates, there is no update for either `atom-ide-debugger-node@0.7.3` or `atom-ide-ui@0.13.0` (Atom itself got updated to 1.31.2 but it does not solve this issue).

If it was not clear: I'm not using [Nuclide](http://nuclide.io/), but [Atom-IDE](https://ide.atom.io/) (Atom with additional packages). If the issue is already fixed in a newer version of Nuclide, could you please release/backport it to the Atom packages?

**Comment by DimaMcar** [comment]
The same problem with me. Check both in Ubuntu and Windows
