### ISSUE TITLE
nuclide-buck unable to find @accent-text-color

### ISSUE THREAD

**Issue by ezh** [facebook/nuclide#1652]
### Issue and Steps to Reproduce
Change default OneDark theme to something other.

### Expected Behavior
Package is working normally

### Actual Behavior
Exception.

### Versions
**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: �������� Windows 10 Pro
**Thrown From**: 'nuclide-buck' package v0.0.0

### Stack Trace

Failed to reload the nuclide-buck package stylesheets

```
At variable @accent-text-color is undefined in C:\Users\Ezh\.atom\packages\nuclide\pkg\nuclide-buck\styles\TaskRunnerStatusComponent.less:36:13

LessError: variable @accent-text-color is undefined
at C:\Users\Ezh\.atom\packages\nuclide\pkg\nuclide-buck\styles\TaskRunnerStatusComponent.less:36:13
```

### Non-Core Packages

```
nuclide 0.366.0 
seti-ui 1.11.0 
```

### Additional Details
* Installed packages (`apm ls --installed`):
apm ls --installed
Community Packages (2) C:\Users\Ezh\.atom\packages
├── nuclide@0.366.0
└── seti-ui@1.11.0

**Comment by robjac** [comment]
[Enter steps to reproduce:]

1. change the syntax theme to anything.

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.6
**Thrown From**: 'nuclide-buck' package v0.0.0


### Stack Trace

Failed to load the nuclide-buck package

```
At variable @accent-text-color is undefined in /Users/robjac/.atom/packages/nuclide/pkg/nuclide-buck/styles/TaskRunnerStatusComponent.less:36:13

LessError: variable @accent-text-color is undefined
at /Users/robjac/.atom/packages/nuclide/pkg/nuclide-buck/styles/TaskRunnerStatusComponent.less:36:13
```

### Commands

```
     -0:01.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
accents-ui 1.3.0 
adventurous-syntax 0.2.0 
aesthetic-ui 4.0.0 
an-old-hope-syntax 1.0.4 
angularjs 0.5.3 
animated-cursor 1.1.0 
apex-ui 1.2.0 
atom-beautify 0.33.4 
atom-bulma 0.7.1 
atom-clock 0.1.16 
atom-csscomb 3.0.0 
atom-gooey-syntax 1.0.0 
atom-handlebars 1.3.0 
atom-ide-ui 0.13.0 
atom-jshint 2.0.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
atom-monokai-dark 0.4.0 
atom-pair 2.0.13 
atom-solarized-dark-ui 0.28.1 
atom-sonic 0.3.2 
atom-sonic-pi 0.1.0 
atom-tachyons 1.6.0 
atom-ternjs 0.18.3 
atom-toolbar 0.1.6 
atom-visual-studio-code-ui 1.3.4 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-clang 0.11.5 
autocomplete-elixir 1.5.16 
autocomplete-erlang 1.1.2 
autocomplete-glsl 0.2.3 
autocomplete-haskell 1.0.1 
autocomplete-java 1.2.7 
autocomplete-json 5.5.2 
autocomplete-php 0.3.7 
autocomplete-ruby 0.2.8 
autocomplete-ruby-rct 0.1.0 
autoprefixer 3.7.1 
base16-eighties-dark 2.1.1 
better-git-blame 0.4.7 
brogrammer-syntax 1.0.0 
brogrammer-ui 1.0.0 
browser-plus 0.0.98 
browser-plus-open-new-window 0.0.1 
browser-plus-zoom 0.0.2 
busy-signal 1.4.3 
chameleon-dark-syntax 0.0.5 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
cobalt2-syntax 0.5.3 
color-picker 2.3.0 
compare-files 0.8.1 
css-declaration-sorter 1.2.3 
css-snippets 1.1.0 
custom-folds 1.9.5 
dark-bint-syntax 0.10.0 
dash 1.7.1 
doge 0.1.3 
double-tag 1.5.0 
dracula-syntax 2.0.7 
dracula-ui 0.6.0 
elm-format 3.2.0 
elm-instant 2.0.0 
elm-navigator 2.0.0 
elm-snippets 0.1.0 
elmjutsu 9.0.3 
ember-cli-helper 0.18.0 
emmet 2.4.3 
emmet-jsx-props 1.4.0 
emmet-snippets-compatibility 1.0.6 
enhanced-tabs 1.7.0 
eval-javascript 1.2.0 
Extempore-Atom 0.4.2 
file-icons 2.1.26 
file-watcher 2.0.0 
flex-tool-bar 2.1.2 
flow-ide 1.12.1 
font-awesome-snippetset 0.0.6 
fonts 3.2.0 
framer-syntax 1.1.0 
framer-ui 2.0.0 
gibber 0.1.3 
git-log 0.4.1 
git-plus 8.1.0 
git-status 0.3.4 
git-time-machine 2.1.0 
gl-light-syntax 3.0.0 
glowing-cursor 0.1.2 
glsl-preview 1.5.0 
gruvbox-plus-syntax 1.3.1 
haskell-ghc-mod 2.2.4 
haskell-grammar 0.4.0 
hey-pane 1.1.2 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.14.0 
hotdog-tabs 1.2.3 
html-to-elm 0.2.0 
hugs-syntax 1.0.0 
hyperclick 0.1.5 
ide-crystal 0.3.3 
ide-css 0.3.0 
ide-flowtype 0.24.0 
ide-haskell 2.3.1 
ide-haskell-cabal 2.2.0 
ide-haskell-hasktags 0.0.15 
ide-haskell-repl 0.8.2 
ide-html 0.4.2 
ide-json 0.2.1 
ide-ruby 0.2.0 
incremental-search 5.2.2 
intentions 1.1.5 
javascript-snippets 1.2.1 
jQuery 1.2.6 
jquery-snippets 11.0.0 
js-hyperclick 1.13.3 
jslint 1.5.1 
jumpy 5.0.2 
KeyCount 0.2.0 
ksx-matrix-ui 1.2.8 
language-babel 2.85.0 
language-crystal-actual 0.37.2 
language-elixir 0.22.1 
language-elm 1.5.0 
language-glsl 2.0.4 
language-graphql 0.11.0 
language-groovy 0.7.0 
language-haml 0.31.1 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-supercollider 0.2.1 
language-swift 0.5.0 
language-thrift 1.0.2 
line-count 0.5.0 
line-diff-details 1.9.0 
linter 2.2.0 
linter-bootlint 1.1.0 
linter-clang 4.1.2 
linter-csslint 2.0.1 
linter-elixirc 1.7.0 
linter-elm-make 0.28.5 
linter-erb 1.1.1 
linter-eslint 8.4.1 
linter-flow 5.6.1 
linter-flowtype 1.0.2 
linter-glsl 2.1.4 
linter-hlint 2.0.0 
linter-htmlhint 1.5.1 
linter-mixed-indent 1.1.1 
linter-rails-best-practices 0.2.2 
linter-rubocop 2.2.3 
linter-ruby 1.2.6 
linter-rust 0.9.0 
linter-sass-lint 1.8.3 
linter-scss-lint 3.1.1 
linter-stylelint 4.3.2 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
linter-xo 0.26.0 
Lucario 2.2.0 
lunar-particle-syntax 0.3.8 
lunar-particle-ui 0.3.13 
material-design-syntax 3.1.2 
miami-nights-syntax 0.3.3 
minimap 4.29.9 
minimap-autohider 1.5.4 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
monokai 0.24.0 
monokai-blackboard 0.3.0 
monokai-dark 1.5.0 
monokai-flat 1.0.1 
monokai-seti 0.9.0 
motepair 0.24.0 
motepair2 0.37.0 
multi-cursor 2.1.5 
neon-color-scheme 1.0.0 
neon-cursor 1.6.0 
neon-syntax 0.3.7 
night-owl-ui 1.0.0 
nova-atom-syntax 1.5.0 
nova-atom-ui 1.3.0 
nucleus-dark-ui 0.12.3 
nuclide 0.366.0 
nuclide-format-js 0.0.47 
oceanic-next 1.0.0 
oceanic-reef-syntax 0.9.0 
octocat-syntax 2.2.3 
open-recent 5.0.0 
open-this 0.5.0 
p5xjs-autocomplete 2.3.0 
package-cop 0.2.10 
package-list 0.1.2 
package-switch 0.5.0 
package-sync 1.1.0 
pane-layout-plus 0.7.4 
path-hyperclick 0.3.0 
pigments 0.40.2 
pipboy-ui 1.0.0 
platformio-ide-terminal 2.8.4 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
prettier-atom 0.55.2 
pristine-ui 1.1.11 
project-colorize 0.3.0 
project-manager 3.3.6 
project-sidebar 1.3.0 
project-view 0.6.5 
pure-syntax 1.0.1 
rails-finder 0.13.0 
rails-snippets 2.19.0 
rails-transporter 1.7.1 
rainbow-tabs 2.5.1 
react 0.18.0 
react-es6-snippets 0.3.0 
react-native-snippets 0.3.0 
react-snippets 1.1.1 
recent-projects 0.13.1 
relative-numbers 0.9.0 
robin-hood-syntax 1.0.0 
rubocop-auto-correct 1.5.1 
ruby-solargraph 0.3.0 
sb-atom-sonic-pi 1.0.0-beta.2 
script 3.18.1 
scss-media-queries 0.4.0 
scss-snippets 0.6.0 
selector-to-tag 0.5.0 
set-syntax 0.4.0 
seti-syntax 1.2.0 
seti-ui 1.11.0 
seti-ui-red 0.13.0 
SkriptDark-Neon-Syntax 2.1.2 
sort-css 0.3.0 
sort-lines 0.18.0 
sorter 1.2.1 
spacegray-dark-syntax 0.2.0 
split-diff 1.5.3 
standard-formatter 2.8.0 
standardjs-snippets 2.6.2 
steam-pirate-syntax 0.3.0 
steam-pirate-ui 0.6.1 
Sublime-Style-Column-Selection 1.7.5 
supercollider 0.9.1 
supercopair 0.10.7 
sync-settings 0.8.6 
tab-smart-sort 0.3.0 
tabs-closer 0.16.0 
tabs-toggle 0.15.0 
teletype 0.13.3 
terminal-syntax 0.1.0 
terminate-syntax 0.3.0 
tidal-autocode 0.6.4 
tidalcycles 0.12.1 
tidy-tabs 0.4.0 
todo-show 2.3.2 
tomorrow 1.0.0 
tomorrow-night-eighties 0.5.0 
tomorrow-night-eighties-syntax 1.1.0 
tool-bar 1.1.11 
tool-bar-almighty 0.8.2 
tree-view-git-status 1.5.2 
triangle-syntax 2.3.0 
ubik-hackerman-syntax 1.10.0 
veda 2.10.2 
vim-mode-plus 1.35.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
zentabs 0.8.9 
```

**Comment by pelmers** [comment]
fixed in e981edc44f3c63ee5bd83df80f914ad38a20bcf4

**Comment by robjac** [comment]
still occurs for me -- what version of nuclide should i be running?

**Comment by robjac** [comment]
@pelmers Still occurs on my system; everything is up to date. seems like my less file still does not have the `@accent-text-color` definition.

**Comment by pelmers** [comment]
The version with the fix is 0.368, I think that's not released yet.

**Comment by robjac** [comment]
Ah gotcha; i could not find the version number in that commit link. I appreciate the reply, and await the release. :)
