### ISSUE TITLE
Uncaught Error: Missing "providerName" property for hyperclick provider.

### ISSUE THREAD

**Issue by noisedispatch** [facebook/nuclide#229]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [hyperclick](https://github.com/facebook/nuclide) package, v1337.0.0-16773830

### Stack Trace

Uncaught Error: Missing "providerName" property for hyperclick provider.

```
At /Users/carlshen/.nuclide/16773830/Tools/Nuclide/pkg/nuclide/hyperclick/lib/main.js:31

Error: Missing "providerName" property for hyperclick provider.
  at Object.consumeProvider (/Users/carlshen/.nuclide/16773830/Tools/Nuclide/pkg/nuclide/hyperclick/lib/main.js:31:13)
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "fuzzy-finder",
      "nuclide-toolbar",
      "tree-view"
    ],
    "audioBeep": false,
    "themes": [
      "northem-dark-atom-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.7
clipboard-plus, v0.5.1
cursor-history, v0.5.5
fb-analytics-client, v1337.0.0-16773830
fb-analytics-reporter-settings, v1337.0.0-16773830
fb-biggrep-provider, v1337.0.0-16773830
fb-codegraph-providers, v1337.0.0-16773830
fb-diffs-and-tasks, v1337.0.0-16773830
fb-error-reporting, v1337.0.0-16773830
fb-file-a-bug, v1337.0.0-16773830
fb-graphql, v1337.0.0-16773830
fb-handle-url, v1337.0.0-16773830
fb-hg-smartlog, v1337.0.0-16773830
fb-home, v1337.0.0-16773830
fb-logging-helper, v1337.0.0-16773830
fb-nuclide-file-creation, v1337.0.0-16773830
fb-nuclide-file-creation-ios, v1337.0.0-16773830
fb-nuclide-installer, v0.1.8
fb-package-manager, v1337.0.0-16773830
fb-phabricator-comments-client, v1337.0.0-16773830
fb-rating, v1337.0.0-16773830
fb-slog-viewer, v1337.0.0-16773830
fb-snippets, v1337.0.0-16773830
fb-test-runner-t-client, v1337.0.0-16773830
haskell-grammar, v0.4.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
hyperclick, v1337.0.0-16773830
language-babel, v0.15.10
language-ini, v1.13.0
language-javascript-jsx, v0.3.7
language-javascript-semantic, v0.2.1
language-ocaml, v1.1.2
language-thrift, v1.0.2
northem-dark-atom-ui, v0.3.0
nuclide-arcanist, v1337.0.0-16773830
nuclide-blame, v1337.0.0-16773830
nuclide-blame-provider-hg, v1337.0.0-16773830
nuclide-blame-ui, v1337.0.0-16773830
nuclide-buck-files, v1337.0.0-16773830
nuclide-busy-signal, v1337.0.0-16773830
nuclide-clang-atom, v1337.0.0-16773830
nuclide-code-format, v1337.0.0-16773830
nuclide-debugger-atom, v1337.0.0-16773830
nuclide-debugger-hhvm, v1337.0.0-16773830
nuclide-debugger-lldb, v1337.0.0-16773830
nuclide-diagnostics-store, v1337.0.0-16773830
nuclide-diagnostics-ui, v1337.0.0-16773830
nuclide-diff-view, v1337.0.0-16773830
nuclide-file-tree, v1337.0.0-16773830
nuclide-file-watcher, v1337.0.0-16773830
nuclide-find-references, v1337.0.0-16773830
nuclide-flow, v1337.0.0-16773830
nuclide-fuzzy-filename-provider, v1337.0.0-16773830
nuclide-hack, v1337.0.0-16773830
nuclide-hack-symbol-provider, v1337.0.0-16773830
nuclide-health, v1337.0.0-16773830
nuclide-hg-repository, v1337.0.0-16773830
nuclide-home, v1337.0.0-16773830
nuclide-language-hack, v1337.0.0-16773830
nuclide-objc, v1337.0.0-16773830
nuclide-ocaml, v1337.0.0-16773830
nuclide-open-filenames-provider, v1337.0.0-16773830
nuclide-quick-open, v1337.0.0-16773830
nuclide-recent-files-provider, v1337.0.0-16773830
nuclide-recent-files-service, v1337.0.0-16773830
nuclide-remote-projects, v1337.0.0-16773830
nuclide-test-runner, v1337.0.0-16773830
nuclide-type-hint, v1337.0.0-16773830
react-snippets, v0.2.0
symbols-tree-view, v0.10.1
toggle-gutter, v0.2.2
tool-bar, v0.1.9
vim-mode, v0.62.0

# Dev
No dev packages
```

**Comment by nmote** [comment]
Looks like the symbols-tree-view package does not include a `providerName` property. Uninstall that package or see if the author will add it so it is compatible with the latest Nuclide.

**Comment by dsifford** [comment]
I'm getting a similar issue @nmote and I'm curious how you were able to decipher what package was causing this by looking at the error log?

Here's mine if you care to check it out...


[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.0-beta6
**System**: Microsoft Windows 10 Pro
**Thrown From**: [hyperclick](https://github.com/facebooknuclideapm/hyperclick) package, v0.0.35


### Stack Trace

Uncaught Error: Missing "providerName" property for hyperclick provider.

```
At C:\Users\dsifford\.atom\packages\hyperclick\lib\main.js:32

Error: Missing "providerName" property for hyperclick provider.
    at Object.consumeProvider (C:\Users\dsifford\.atom\packages\hyperclick\lib\main.js:32:13)
    at Provider.module.exports.Provider.provide (C:\Users\dsifford\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at C:\Users\dsifford\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-flake8",
      "linter-flake8",
      "markdown-preview",
      "spell-check"
    ],
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ],
    "audioBeep": false,
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "go-plus",
      "fuzzy-finder"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-alignment, v0.12.1
autocomplete-go, v0.0.3
autohide-tree-view, v0.25.1
chester-atom-syntax, v0.1.1
color-picker, v2.0.13
docblockr, v0.7.3
emmet, v2.3.15
express-complete, v0.2.0
go-config, v0.2.4
go-plus, v3.5.2
highlight-line, v0.11.0
highlight-selected, v0.11.1
hyperclick, v0.0.35
jquery-snippets, v11.0.0
js-hyperclick, v1.4.0
language-docker, v1.1.3
language-jade, v0.6.2
language-latex, v0.6.1
linter, v1.11.2
linter-jshint, v1.2.1
markdown-preview-plus, v2.2.2
mathjax-wrapper, v0.1.0
minimap, v4.16.2
minimap-highlight-selected, v4.3.1
pdf-view, v0.36.0
pigments, v0.19.1
set-syntax, v0.3.0
seti-icons, v0.4.5
Sublime-Style-Column-Selection, v1.3.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by raboof** [comment]
I'm running into the same issue. 

Is the `providerName` really so important that Nuclide cannot function when there is a package installed that doesn't have it?

**Comment by ssorallen** [comment]
@nmote It seems reasonable to generate a unique name if the provider doesn't create one. Hyperclick doesn't seem to care what the string is, so it shouldn't matter to the rest of the code anyway. It can be generated once when the service is consumed.

**Comment by claytonrcarter** [comment]
I was getting the same when trying to use the ["official" demo package](https://github.com/oclbdk/hyperclick-provider-demo).  I tracked it down to that package offering two providers via an array at the end of it's [main.js](https://github.com/oclbdk/hyperclick-provider-demo/blob/master/lib/main.js):
```
module.exports = {
  getProvider() {
    return [ singleSuggestionProvider, multiSuggestionProvider ];
  },
};
```
Changing that to just pass in one or the other of those providers fixed the problem.  (I had added `providerNames` to both of them.)

I'm definitely no expert here, but it looks to me that that the hyperclick package is looking for a `provider.providerName` property when it loads providers.  (ie it's not expecting an array)  But then, right below that, it passes the provider to `hyperclick.consumeProvider()`, which looks like it is flexible enough to accept either a single provider, or an array of them.  So if I'm reading this right, even though each of the providers above were correctly structured, they bombed because of this inconsistency.

Sorry if I'm off base; Node and Coffeescript are still quite new to me.  Am I close? Thanks, Clayton

Relevant section of [main.js, lines 30+](https://github.com/facebooknuclideapm/hyperclick/blob/daa1fa160f8896433aced971dd87b232e17783da/lib/main.js):
```
  consumeProvider: function consumeProvider(provider) {
    if (typeof provider.providerName !== 'string') {
      throw new Error('Missing "providerName" property for hyperclick provider.');
    }
    if (hyperclick != null) {
      hyperclick.consumeProvider(provider);
      return new _atom.Disposable(function () {
        if (hyperclick != null) {
          hyperclick.removeProvider(provider);
        }
      });
    }
  },
```
and relevant section of [Hyperclick.js, lines 104+](https://github.com/facebooknuclideapm/hyperclick/blob/daa1fa160f8896433aced971dd87b232e17783da/lib/Hyperclick.js):
```
    key: '_applyToAll',
    value: function _applyToAll(item, f) {
      if (Array.isArray(item)) {
        item.forEach(function (x) {
          return f(x);
        });
      } else {
        f(item);
      }
    }
  }, {
    key: 'consumeProvider',
    value: function consumeProvider(provider) {
      var _this2 = this;

      this._applyToAll(provider, function (singleProvider) {
        return _this2._consumeSingleProvider(singleProvider);
      });
    }
  }
```

**Comment by nmote** [comment]
This sounds plausible, and we should have been more careful when changing this API. We definitely should have bumped the API version, and probably should have thought more carefully about whether to make this mandatory. It's used only to gather performance data from our internal users, so it doesn't even have an affect on users outside of Facebook. I think that's a good case for making it optional.

I'll likely just make it optional but a PR would help move things along :)

**Comment by dsifford** [comment]
@nmote - Has there been any updates on this? Still getting this error on Linux as well as Nuclide as a whole being an ostensible system-hog. Would like to start fiddling with flow.....

**Comment by bsr203** [comment]
Installed the latest 

Atom 1.4.0
Nuclide: 0.111.0
OS: Mac OSX 10.9.5
 node --version                                                                                                            master ✱
v4.0.0


```
Uncaught Error: Missing "providerName" property for hyperclick provider.
/Users/bsr/.atom/packages/nuclide/pkg/nuclide/hyperclick/lib/main.js:30
Hide Stack Trace
Error: Missing "providerName" property for hyperclick provider.
    at Object.consumeProvider (/Users/bsr/.atom/packages/nuclide/pkg/nuclide/hyperclick/lib/main.js:30:13)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
```

**Comment by mostafaeweda** [comment]
I just double-verified that all hyperclick providers now have the `providerName` property.
Hence, I'm pretty sure this is fixed with our latest UP release, see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/

**Comment by ssorallen** [comment]
This is still an issue. The Hyperclick provider than originally caused this issue was not owned by Facebook. (see https://github.com/ensime/ensime-atom/issues/102)

There's a change being reviewed internally currently to make the name optional.

**Comment by ches** [comment]
Will this fix from 548d1aa be applied in the standalone `hyperclick` package?

**Comment by nmote** [comment]
No. Our move to the unified package deprecates all of the individual Nuclide packages, including `hyperclick`. There is some interest in splitting `hyperclick` out again and possibly attempting to get it included with Atom but at the moment we have no concrete plans.

Currently we recommend that you install the `nuclide` package. If you truly only want `hyperclick` you can disable the other parts of Nuclide, although we are primarily interested in supporting people who want to use Nuclide as a whole.

**Comment by ches** [comment]
Thanks for making this clear @nmote. I read about the unified packaging but the post alluded to the `nuclide-*` packages, so I wasn't certain.

My work doesn't have much to do with the languages that are currently Nuclide's main focuses, but I am using a package (actually two or three I believe) that utilize the standalone `hyperclick`, so I'd be among those interested in seeing its separate maintenance carried on in some way. It does seem to have clear general, cross-cutting utility.

**Comment by nmote** [comment]
Yeah, like I said we've been musing for quite a while about getting it bundled with Atom but nobody has made the time to push it forward. We'd still like to do it, it's just not a top priority at the moment. There was a PR against Atom a while back where the Atom team outlined what would need to get done:

https://github.com/atom/atom/pull/6843

Since the unified package transition `hyperclick` has become a little bit more rooted within Nuclide. It would require some effort to tear it out but it's certainly tractable.

CC @joefitzgerald who I have also chatted with about this.

**Comment by santiagobasulto** [comment]
I just ran through the same issue:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [hyperclick](https://github.com/facebooknuclideapm/hyperclick) package, v0.0.35


### Stack Trace

Uncaught Error: Missing "providerName" property for hyperclick provider.

```
At /Users/santiagobasulto/.atom/packages/hyperclick/lib/main.js:32

Error: Missing "providerName" property for hyperclick provider.
    at Object.consumeProvider (/Users/santiagobasulto/.atom/packages/hyperclick/lib/main.js:32:13)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -0:52.9.0 core:cancel (a.stack-toggle)
     -0:51.1.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autosave",
      "atomic-emacs"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
autocomplete-python, v1.7.0
emmet, v2.4.1
file-icons, v1.6.17
highlight-line, v0.11.1
highlight-selected, v0.11.2
hyperclick, v0.0.35
linter, v1.11.3
linter-flake8, v1.12.0
pigments, v0.24.2
symbols-tree-view, v0.11.0

# Dev
No dev packages
```
