### ISSUE TITLE
Uncaught Error: not opened

### ISSUE THREAD

**Issue by tagpro** [facebook/nuclide#508]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.138.0
### Stack Trace

Uncaught Error: not opened

```
At /Users/hasher/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:218

Error: not opened
  at WebSocket.send (/Users/hasher/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:218:16)
  at FrontendClient._sendMessage (/Users/hasher/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/FrontendClient.js:62:20)
  at FrontendClient.sendEvent (/Users/hasher/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/FrontendClient.js:114:10)
  at FrontendClient.sendInspectorDetached (/Users/hasher/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/FrontendClient.js:169:8)
  at CustomSession.Session._onDebuggerClientClose (/Users/hasher/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/session.js:48:25)
  at emitOne (events.js:82:20)
  at DebuggerClient.emit (events.js:169:7)
  at DebuggerClient._onConnectionClose (/Users/hasher/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/DebuggerClient.js:91:8)
  at emitOne (events.js:77:13)
  at Debugger.emit (events.js:169:7)
  at Debugger._onConnectionClose (/Users/hasher/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/debugger.js:79:8)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at TCP._onclose (net.js:469:12)

```
### Commands

```
     -2:26.4.0 nuclide-debugger:stop-debugging (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:26.2.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:25.6.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:24.7.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:24.7.0 nuclide-console:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:24.6.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:17.2.0 pane:show-item-2 (atom-pane.pane.active)
     -0:10.9.0 command-palette:toggle (atom-pane.pane.active)
     -0:07.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.4.0 nuclide-react-native:start-debugging (atom-pane.pane.active)
     -0:07.4.0 nuclide-debugger:stop-debugging (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.3.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.3.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.1.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.1.0 nuclide-console:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```
### Installed Packages

``` coffee
# User
nuclide, v0.138.0

# Dev
No dev packages
```

**Comment by shushz** [comment]
@yinghuitan, it seems to be related to debugger - could you take a look?

**Comment by yinghuitan** [comment]
@tagpro, I tried react native debugging, but was unable to reproduce this error. Can you provide detailed reproduce steps for this error?

**Comment by tagpro** [comment]
@yinghuitan - I got this error again when I tried to start react native
debugger(React Native: Start Debugging).

On Sat, May 21, 2016 at 1:59 AM, yinghuitan <notifications@github.com>
wrote:

> @tagpro <https://github.com/tagpro>, I tried react native debugging, but
> was unable to reproduce this error. Can you provide detailed reproduce
> steps for this error?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/nuclide/issues/508#issuecomment-220710770>
>



-- 
regards
Jaspreet Singh | 9790550185

**Comment by tagpro** [comment]
Sorry, I forgot to mention - My debugger was already running and I tried to
start debugging again.

Regards

On Wed, May 25, 2016 at 3:51 PM, Jaspreet Singh <jaspreet.singh@hashedin.com
> wrote:

> @yinghuitan - I got this error again when I tried to start react native
> debugger(React Native: Start Debugging).
>
> On Sat, May 21, 2016 at 1:59 AM, yinghuitan <notifications@github.com>
> wrote:
>
>> @tagpro <https://github.com/tagpro>, I tried react native debugging, but
>> was unable to reproduce this error. Can you provide detailed reproduce
>> steps for this error?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/facebook/nuclide/issues/508#issuecomment-220710770>
>>
>
>
>
> --
> regards
> Jaspreet Singh | 9790550185
>



-- 
regards
Jaspreet Singh | 9790550185

**Comment by tagpro** [comment]
It reproduced on different machine again when I tried to close the react native debugger and the debugger was not connected - see the issue below.
 
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Ubuntu 14.04.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.136.0


### Stack Trace

Uncaught Error: not opened

```
At /home/jazz/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:218

Error: not opened
  at WebSocket.send (/home/jazz/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:218:16)
  at FrontendClient._sendMessage (/home/jazz/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/FrontendClient.js:62:20)
  at FrontendClient.sendEvent (/home/jazz/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/FrontendClient.js:114:10)
  at FrontendClient.sendInspectorDetached (/home/jazz/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/FrontendClient.js:169:8)
  at CustomSession.Session._onDebuggerClientClose (/home/jazz/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/session.js:48:25)
  at emitOne (events.js:82:20)
  at DebuggerClient.emit (events.js:169:7)
  at DebuggerClient._onConnectionClose (/home/jazz/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/DebuggerClient.js:91:8)
  at emitOne (events.js:77:13)
  at Debugger.emit (events.js:169:7)
  at Debugger._onConnectionClose (/home/jazz/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node-inspector/lib/debugger.js:79:8)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at TCP._onclose (net.js:469:12)

```

### Commands

```
     -0:16.3.0 command-palette:toggle (button.btn.icon.icon-gear)
     -0:11.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:09.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:08.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:07.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```

### Installed Packages

```coffee
# User
egghead-react-snippets, v1.1.1
language-javascript-better, v1.7.1
language-javascript-jsx, v0.3.7
minimap, v4.23.5
nuclide, v0.136.0

# Dev
No dev packages
```

**Comment by yinghuitan** [comment]
@matthewwithanm, can you help @tagpro  with this? Thanks.

**Comment by matthewwithanm** [comment]
Sure thing!

@tagpro So are you saying that you were already successfully debugging, but then ran the "React Native: Start Debugging" command again and that's when you saw this?

**Comment by tagpro** [comment]
Yeah, that was the state. 
Not just that, it happened to me again when I closed the debugger. At that point of time, my debug js remotely was disabled from my android emulator and then I clicked on the cross button, it again showed me this issue. I am using Ubuntu 14.04 on my system, if that helps. It happened to me 3-4 times in the last one week. I am surprised that I am the only one here... :)

**Comment by matthewwithanm** [comment]
I've seen this error pop up in the console before and pushed 029c0e561f8cfb086f002ed3fc76867fa38f49b7—which should be in next week's release—a few days ago to work around it. I'll try your repro steps and see if it still exists after that commit!

**Comment by nmote** [comment]
@matthewwithanm @tagpro: is this fixed now?

**Comment by Agusum** [comment]
I'm still encountering the issue:

Atom Version: 1.12.6
System: Mac OS X 10.11.6
Thrown From: nuclide package, v0.186.0

## Stack Trace

Uncaught Error: not opened

```
/Users/agusv/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:219

Error: not opened
  at WebSocket.send (/Users/agusv/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:219:16)
  at FrontendClient._sendMessage (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:62:20)
  at FrontendClient.sendResponse (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:91:8)
  at Object._handleMethodResult (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:196:26)
  at Object.<anonymous> (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:170:12)
  at /Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node_modules/async/lib/async.js:148:21
  at /Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerClient.js:116:7
  at Object.request (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerClient.js:12:7)
  at DebuggerClient.request (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerClient.js:113:14)
  at Object.<anonymous> (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerAgent.js:328:30)
  at iterate (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node_modules/async/lib/async.js:146:13)
  at Object.async.eachSeries (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node_modules/async/lib/async.js:162:9)
  at Object.setPauseOnExceptions (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerAgent.js:325:11)
  at Object.handleCommand (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:169:12)
  at Object._handleFrontendMessage (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:128:10)
  at emitOne (events.js:96:13)
  at FrontendClient.emit (events.js:188:7)
  at FrontendClient._onConnectionMessage (/Users/agusv/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:40:8)
  at emitTwo (events.js:106:13)
  at WebSocket.emit (events.js:191:7)
  at Receiver.ontext (/Users/agusv/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:841:10)
  at /Users/agusv/.atom/packages/nuclide/node_modules/ws/lib/Receiver.js:536:18
  at /Users/agusv/.atom/packages/nuclide/node_modules/ws/lib/Receiver.js:368:7
  at /Users/agusv/.atom/packages/nuclide/node_modules/ws/lib/PerMessageDeflate.js:249:5
  at afterWrite (_stream_writable.js:361:3)
  at onwrite (_stream_writable.js:352:7)
  at WritableState.onwrite (_stream_writable.js:89:5)
  at afterTransform (_stream_transform.js:79:3)
  at TransformState.afterTransform (_stream_transform.js:54:12)
  at Zlib.callback (zlib.js:639:5)
```

**Comment by jeroenbe** [comment]
Hi, Any progress on this? I'm trying to debug a regular NodeJS app.

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.205.0


### Stack Trace

Uncaught Error: not opened

```
At /Users/Jeroen/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:219

Error: not opened
  at WebSocket.send (/packages/nuclide/node_modules/ws/lib/WebSocket.js:219:16)
  at FrontendClient._sendMessage (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:62:20)
  at FrontendClient.sendResponse (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:91:8)
  at Object._handleMethodResult (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:196:26)
  at Object.handleCommand (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:148:12)
  at Object._handleFrontendMessage (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:128:10)
  at emitOne (events.js:96:13)
  at FrontendClient.emit (events.js:188:7)
  at FrontendClient._onConnectionMessage (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:40:8)
  at emitTwo (events.js:106:13)
  at WebSocket.emit (events.js:191:7)
  at Receiver.ontext (/packages/nuclide/node_modules/ws/lib/WebSocket.js:841:10)
  at /packages/nuclide/node_modules/ws/lib/Receiver.js:536:18
  at /packages/nuclide/node_modules/ws/lib/Receiver.js:368:7
  at /packages/nuclide/node_modules/ws/lib/PerMessageDeflate.js:249:5
  at afterWrite (_stream_writable.js:361:3)
  at onwrite (_stream_writable.js:352:7)
  at WritableState.onwrite (_stream_writable.js:89:5)
  at afterTransform (_stream_transform.js:79:3)
  at TransformState.afterTransform (_stream_transform.js:54:12)
  at Zlib.callback (zlib.js:639:5)
```

**Comment by wlinglinux** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.210.0


### Stack Trace

Uncaught Error: not opened

```
At /Users/wlingliuux/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:356

Error: not opened
  at WebSocket.send (/packages/nuclide/node_modules/ws/lib/WebSocket.js:356:18)
  at FrontendClient._sendMessage (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:62:20)
  at FrontendClient.sendResponse (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:91:8)
  at Object._handleMethodResult (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:196:26)
  at Object.handleCommand (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:148:12)
  at Object._handleFrontendMessage (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:128:10)
  at emitOne (events.js:96:13)
  at FrontendClient.emit (events.js:188:7)
  at FrontendClient._onConnectionMessage (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:40:8)
  at emitTwo (events.js:106:13)
  at WebSocket.emit (events.js:191:7)
  at Receiver._receiver.onmessage (/packages/nuclide/node_modules/ws/lib/WebSocket.js:143:54)
  at Receiver.dataMessage (/packages/nuclide/node_modules/ws/lib/Receiver.js:385:14)
  at Receiver.getData (/packages/nuclide/node_modules/ws/lib/Receiver.js:333:12)
  at Receiver.startLoop (/packages/nuclide/node_modules/ws/lib/Receiver.js:155:19)
  at Receiver.add (/packages/nuclide/node_modules/ws/lib/Receiver.js:134:10)
  at Socket._ultron.on (/packages/nuclide/node_modules/ws/lib/WebSocket.js:139:22)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at TCP.onread (net.js:543:20)

```

### Commands

```
     -4:56.5.0 nuclide-debugger:remove-all-breakpoints (span.nuclide-debugger-breakpoint)
     -4:54.8.0 nuclide-debugger:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:42.8.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:42.8.0 nuclide-debugger:toggle-launch-attach (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:42.7.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:42.7.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:47.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -2:16.3.0 go-to-line:toggle (input.hidden-input)
     -2:13.3.0 core:confirm (input.hidden-input)
 57x -2:07.2.0 core:move-up (input.hidden-input)
 20x -1:37.6.0 core:move-down (input.hidden-input)
     -1:28.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.12.0 
language-babel 2.56.2 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
merge-conflicts 1.4.4 
nuclide 0.210.0 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by yacut** [comment]
1. Open Atom
2. Run some node script in debug mode: `node --inspect-brk index.js`
3. Attach debugger to running node script.
4. Error occurred.

```
$ node -v
v8.1.2
$ npm -v
5.0.3
```

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.232.0


### Stack Trace

Uncaught Error: not opened

```
At /Users/roman/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:356

Error: not opened
  at WebSocket.send (/packages/nuclide/node_modules/ws/lib/WebSocket.js:356:18)
  at FrontendClient._sendMessage (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:62:20)
  at FrontendClient.sendResponse (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:91:8)
  at Object._handleMethodResult (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:196:26)
  at /packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:170:12)
  at /packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node_modules/async/lib/async.js:148:21
  at /packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerClient.js:116:7
  at Object.request (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerClient.js:12:7)
  at DebuggerClient.request (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerClient.js:113:14)
  at /packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerAgent.js:328:30)
  at iterate (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node_modules/async/lib/async.js:146:13)
  at Object.async.eachSeries (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node_modules/async/lib/async.js:162:9)
  at Object.setPauseOnExceptions (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerAgent.js:325:11)
  at Object.handleCommand (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:169:12)
  at Object._handleFrontendMessage (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendCommandHandler.js:128:10)
  at emitOne (events.js:96:13)
  at FrontendClient.emit (events.js:188:7)
  at FrontendClient._onConnectionMessage (/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/FrontendClient.js:40:8)
  at emitTwo (events.js:106:13)
  at WebSocket.emit (events.js:191:7)
  at Receiver._receiver.onmessage (/packages/nuclide/node_modules/ws/lib/WebSocket.js:143:54)
  at Receiver.dataMessage (/packages/nuclide/node_modules/ws/lib/Receiver.js:385:14)
  at Receiver.getData (/packages/nuclide/node_modules/ws/lib/Receiver.js:333:12)
  at Receiver.startLoop (/packages/nuclide/node_modules/ws/lib/Receiver.js:155:19)
  at Receiver.add (/packages/nuclide/node_modules/ws/lib/Receiver.js:134:10)
  at Socket._ultron.on (/packages/nuclide/node_modules/ws/lib/WebSocket.js:139:22)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at TCP.onread (net.js:543:20)

```

### Commands

```
     -0:46.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:34.7.0 command-palette:toggle (div.package-detail.panels-item)
     -0:32.4.0 core:move-down (input.hidden-input)
     -0:32 core:confirm (input.hidden-input)
     -0:32 nuclide-debugger:show (div.package-detail.panels-item)
     -0:10.5.0 nuclide-debugger:show-attach-dialog (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -0:08.4.0 core:confirm (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -0:08.3.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -0:07.8.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
hyperclick 0.1.1 
js-hyperclick 1.11.0 
nuclide 0.232.0 
```

**Comment by yacut** [comment]
@pascalc I just tried with node 7.10.0. This does not work for me!

**Comment by mostafaeweda** [comment]
The newly integrated Node debugger should work for newer node versions.

**Comment by MirzaAhmadBilal** [comment]
downgrade your react  native version and i am pretty sure you will go to goo :)
