### ISSUE TITLE
"Couldn't find a react native project" after upgrade to 0.160.0

### ISSUE THREAD

**Issue by danfairs** [facebook/nuclide#663]
### Issue and Steps to Reproduce
Had a react native project working fine with the previous version of Nuclide (0.158.0 - from memory?) Upgraded to 0.160.0 this morning, and I'm unable to run the packager from inside Atom - I receive an error: "Couldn't find a React Native project - Make sure that your current working root (or its ancestor) contains a "node_modules" directory with react-native installed, or a .buckconfig file with a "[react-native]" section that has a "server" key."

Creating the mentioned .buckconfig file - with both an absolute or relative path to packager.sh - doesn't fix the problem. (This wasn't necessary with the previous version).

I'm able to start the packager manually via `react-native run-ios`, and the debugger within Atom also continues to work.

### Expected Behavior
Packager should start.

### Actual Behavior
Receive above error.

### Versions
* Atom: 1.9.6
* Nuclide: 0.160.0
* Client OS: Mac OS X 10.11.6
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
$ apm ls --installed
Community Packages (1) /Users/dan/.atom/packages
└── nuclide@0.160.0

└── (empty)

**Comment by matthewwithanm** [comment]
Hi @danfairs! A few questions:

- Do you have multiple roots open in your file tree?
- If so, which one is selected as the working root? (It will have a briefcase icon instead of a folder)
- Where is your node_modules directory relative to your working root?
- Where is the package.json relative to your working root?
- Does your package.json include react-native as a dependency?
- Is react-native installed in your node_modules directory?

Thanks!

**Comment by levito** [comment]
Hi @matthewwithanm, I can reproduce @danfairs' issue after upgrading nuclide from 0.159.0 to 0.160.0.

- one root open in the file tree
- node_modules and package.json are at project root
- "react-native": "^0.30.0" is there as dependency and installed

**Versions**
- Atom 1.8.0 (Nuclide is still not fully compatible to Atom 1.9, right?)
- Mac OS X 10.11.5

The error occurs when trying to start the react-native packager.

**Comment by matthewwithanm** [comment]
Thanks all. I've found the issue and a fix is on the way! Sorry about this.

> Atom 1.8.0 (Nuclide is still not fully compatible to Atom 1.9, right?)

Yeah, that's right.

**Comment by matthewwithanm** [comment]
Okay, I just pushed v0.161.0 with the fix. Let me know if there are still issues and thanks for reporting!

**Comment by danfairs** [comment]
Hi! Thanks for the quick response :)

I'm still seeing a (different) problem:

```
An unexpected error occurred while running the React Native Packager process:

Packager exited with non-zero exit code (1)

Error: Packager exited with non-zero exit code (1)
  at c.project (/Users/dan/.atom/packages/nuclide/pkg/nuclide-react-native/lib/packager/PackagerActivation.js:191:89)
  at c._next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:325:140)
  at c.e.next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.notifyNext (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:326:282)
  at b._next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.notifyNext (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:275:183)
  at b._next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.notifyNext (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:275:183)
  at b._next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.e._next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:401)
  at c.e.next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at e._next (/Users/dan/.atom/packages/nuclide/pkg/commons-node/stream.js:322:16)
  at e.__tryOrUnsub (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:50:141)
  at e.next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:49:63)
  at e._next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:401)
  at e.next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.b.notifyNext (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:16:355)
  at b._next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.b.notifyNext (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:16:355)
  at b._next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c._subscribe (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:18:369)
  at c.a.subscribe (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:14:53)
  at e._subscribe (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:110:227)
  at e.a.subscribe (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:14:53)
  at Object.f.subscribeToResult (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:432:212)
  at c._next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:271:261)
  at c.notifyComplete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:272:31)
  at b._complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:516)
  at b.e.complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:228)
  at c.notifyComplete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:272:101)
  at b._complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:516)
  at b.e.complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:228)
  at d.e._complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:48:29)
  at d.e.complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:228)
  at e._complete (/Users/dan/.atom/packages/nuclide/pkg/commons-node/stream.js:93:24)
  at e.__tryOrUnsub (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:50:141)
  at e.complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:50:45)
  at e._complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:48:29)
  at e.complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:228)
  at d.e._complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:48:29)
  at d.e.complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:228)
  at c.e._complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:48:29)
  at c.e.complete (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:228)
  at c.notifyNext (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:335:15)
  at b._next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at Socket.<anonymous> (/Users/dan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:123:196)
  at emitNone (events.js:85:20)
  at Socket.emit (events.js:179:7)
  at endReadableNT (_stream_readable.js:913:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

I hadn't realised that Atom 1.9.x was a no-go - I'll downgrade to see if the problem still occurs there for me.

**Comment by danfairs** [comment]
OK, I still get the problem with Atom 1.8.0. Should I open a new ticket for this?

**Comment by matthewwithanm** [comment]
😞 Yeah, please open a new one.
