### ISSUE TITLE
Fuzzy Finder / OmniSearch indexes nonstop with GitHub repo

### ISSUE THREAD

**Issue by imwithsam** [facebook/nuclide#794]
### Issue and Steps to Reproduce
1. Add a local project folder.
2. Bring up Fuzzy Finder / OmniSearch and search for anything.
### Expected Behavior
- Fuzzy Finder / OmniSearch should list suggested files.
### Actual Behavior
- Fuzzy Finder / OmniSearch displays no results and a GitHub logo spinner with a Loading... status.  
- In the bottom status bar next to the git branch name, there is also a GitHub logo spinner. When hovering over the spinner, a tooltip indicates it is indexing files. It never stops indexing.
### Versions
- Atom: 1.12.0-beta0
- Nuclide: 0.175.0
- Client OS: macOS 10.11.6
- Server OS (optional): n/a
### Additional Details
- This happens even with small codebases.
- Fuzzy Finder works fine when Nuclide package is disabled.

**Comment by imwithsam** [comment]
![screenshot-1](https://cloud.githubusercontent.com/assets/1934074/19298847/8561c918-9005-11e6-8b30-dbb6791319ca.jpg)
![screenshot-2](https://cloud.githubusercontent.com/assets/1934074/19298850/8bbf00f0-9005-11e6-9f88-320bb56f3dd9.jpg)

**Comment by hansonw** [comment]
Could you upload your logs somewhere so we can see if anything sticks out there?
They should be available at `$TMPDIR/nuclide-$USER-logs/nuclide.log-2016-*`.

**Comment by imwithsam** [comment]
```
2016-10-12 18:03:10.300 DEBUG (pid:1534) nuclide - Created new remote atom config at /var/folders/1t/ry79x2ln1jnd2lm2jc8vktb40000gp/T/.nuclide/command-server/0 for port 49834 family IPv4
2016-10-12 18:03:10.982 ERROR (pid:1594) nuclide - Failed to load native fuzzy matching. Falling back to JS implementation { Error: Cannot find module '/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/VendorLib/fuzzy-native/build/fuzzy-native/v0.5.1/node-v49-darwin-x64/fuzzy-native.node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/VendorLib/fuzzy-native/lib/main.js:7:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
  code: 'MODULE_NOT_FOUND',
  stackTrace: 
   [ { functionName: 'Module._resolveFilename',
       methodName: '_resolveFilename',
       fileName: 'module.js',
       lineNumber: 440,
       columnNumber: 15,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module._load',
       methodName: '_load',
       fileName: 'module.js',
       lineNumber: 388,
       columnNumber: 25,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module.require',
       methodName: 'require',
       fileName: 'module.js',
       lineNumber: 468,
       columnNumber: 17,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'require',
       methodName: null,
       fileName: 'internal/module.js',
       lineNumber: 20,
       columnNumber: 19,
       evalOrigin: 'internal/module.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/VendorLib/fuzzy-native/lib/main.js',
       lineNumber: 7,
       columnNumber: 18,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/VendorLib/fuzzy-native/lib/main.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module._compile',
       methodName: '_compile',
       fileName: 'module.js',
       lineNumber: 541,
       columnNumber: 32,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module._extensions..js',
       methodName: '.js',
       fileName: 'module.js',
       lineNumber: 550,
       columnNumber: 10,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module.load',
       methodName: 'load',
       fileName: 'module.js',
       lineNumber: 458,
       columnNumber: 32,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'tryModuleLoad',
       methodName: null,
       fileName: 'module.js',
       lineNumber: 417,
       columnNumber: 12,
       evalOrigin: 'module.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module._load',
       methodName: '_load',
       fileName: 'module.js',
       lineNumber: 409,
       columnNumber: 3,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false } ] }
2016-10-12 18:03:14.661 ERROR (pid:1534) nuclide - Failed to load native fuzzy matching. Falling back to JS implementation { Error: Cannot find module '/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/VendorLib/fuzzy-native/build/fuzzy-native/v0.5.1/node-v49-darwin-x64/fuzzy-native.node'
    at Module._resolveFilename (module.js:440:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:388:25)
    at Object.<anonymous> (/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/VendorLib/fuzzy-native/lib/main.js:7:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Object.<anonymous> (/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/lib/main.js:22:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at _load_nuclideFuzzyNative (/Users/samson/.atom/packages/nuclide/pkg/nuclide-open-filenames-provider/lib/OpenFileNameProvider.js:20:32)
    at getOpenTabsMatching (/Users/samson/.atom/packages/nuclide/pkg/nuclide-open-filenames-provider/lib/OpenFileNameProvider.js:25:45)
    at Object.executeQuery (/Users/samson/.atom/packages/nuclide/pkg/nuclide-open-filenames-provider/lib/OpenFileNameProvider.js:68:28)
    at _loop3 (/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:446:98)
    at SearchResultManager.executeQuery (/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:457:9)
    at Object.ID_1 (/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:190:20)
    at QuickSelectionDispatcher._invokeCallback (/Users/samson/.atom/packages/nuclide/pkg/commons-node/Dispatcher.js:214:26)
    at QuickSelectionDispatcher.dispatch (/Users/samson/.atom/packages/nuclide/pkg/commons-node/Dispatcher.js:188:16)
    at Object.query (/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionActions.js:26:91)
    at QuickSelectionComponent.setQuery (/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:580:73)
    at Immediate.<anonymous> (/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:177:31)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
  code: 'MODULE_NOT_FOUND',
  stackTrace: 
   [ { functionName: 'Module._resolveFilename',
       methodName: null,
       fileName: 'module.js',
       lineNumber: 440,
       columnNumber: 15,
       evalOrigin: 'module.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module._resolveFilename',
       methodName: null,
       fileName: '/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js',
       lineNumber: 35,
       columnNumber: 12,
       evalOrigin: '/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module._resolveFilename',
       methodName: '_resolveFilename',
       fileName: '/Applications/Atom Beta.app/Contents/Resources/app.asar/src/module-cache.js',
       lineNumber: 383,
       columnNumber: 52,
       evalOrigin: '/Applications/Atom Beta.app/Contents/Resources/app.asar/src/module-cache.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module._load',
       methodName: '_load',
       fileName: 'module.js',
       lineNumber: 388,
       columnNumber: 25,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/VendorLib/fuzzy-native/lib/main.js',
       lineNumber: 7,
       columnNumber: 18,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/VendorLib/fuzzy-native/lib/main.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module.load',
       methodName: 'load',
       fileName: 'module.js',
       lineNumber: 458,
       columnNumber: 32,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'tryModuleLoad',
       methodName: null,
       fileName: 'module.js',
       lineNumber: 417,
       columnNumber: 12,
       evalOrigin: 'module.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module._load',
       methodName: '_load',
       fileName: 'module.js',
       lineNumber: 409,
       columnNumber: 3,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/lib/main.js',
       lineNumber: 22,
       columnNumber: 20,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/lib/main.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module.load',
       methodName: 'load',
       fileName: 'module.js',
       lineNumber: 458,
       columnNumber: 32,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'tryModuleLoad',
       methodName: null,
       fileName: 'module.js',
       lineNumber: 417,
       columnNumber: 12,
       evalOrigin: 'module.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Module._load',
       methodName: '_load',
       fileName: 'module.js',
       lineNumber: 409,
       columnNumber: 3,
       evalOrigin: 'module.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: '_load_nuclideFuzzyNative',
       methodName: null,
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-open-filenames-provider/lib/OpenFileNameProvider.js',
       lineNumber: 20,
       columnNumber: 32,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-open-filenames-provider/lib/OpenFileNameProvider.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'getOpenTabsMatching',
       methodName: null,
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-open-filenames-provider/lib/OpenFileNameProvider.js',
       lineNumber: 25,
       columnNumber: 45,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-open-filenames-provider/lib/OpenFileNameProvider.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'executeQuery',
       methodName: 'executeQuery',
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-open-filenames-provider/lib/OpenFileNameProvider.js',
       lineNumber: 68,
       columnNumber: 28,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-open-filenames-provider/lib/OpenFileNameProvider.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: '_loop3',
       methodName: null,
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js',
       lineNumber: 446,
       columnNumber: 98,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'executeQuery',
       methodName: 'executeQuery',
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js',
       lineNumber: 457,
       columnNumber: 9,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: 'ID_1',
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js',
       lineNumber: 190,
       columnNumber: 20,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: '_invokeCallback',
       methodName: '_invokeCallback',
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/commons-node/Dispatcher.js',
       lineNumber: 214,
       columnNumber: 26,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/commons-node/Dispatcher.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'dispatch',
       methodName: 'dispatch',
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/commons-node/Dispatcher.js',
       lineNumber: 188,
       columnNumber: 16,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/commons-node/Dispatcher.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'query',
       methodName: 'query',
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionActions.js',
       lineNumber: 26,
       columnNumber: 91,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionActions.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'setQuery',
       methodName: 'setQuery',
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js',
       lineNumber: 580,
       columnNumber: 73,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js',
       lineNumber: 177,
       columnNumber: 31,
       evalOrigin: '/Users/samson/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'tryOnImmediate',
       methodName: null,
       fileName: 'timers.js',
       lineNumber: 546,
       columnNumber: 5,
       evalOrigin: 'timers.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'processImmediate',
       methodName: '_immediateCallback',
       fileName: 'timers.js',
       lineNumber: 525,
       columnNumber: 5,
       evalOrigin: 'timers.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false } ],
  rawStack: 
   [ CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {} ] }
```

**Comment by hansonw** [comment]
Oh.. just realized you're on Atom 1.12. We don't support that yet, unfortunately. (Looks like we need to build some new binaries, but I'm working on it)

**Comment by imwithsam** [comment]
Ok, should I close this issue or leave it open?

**Comment by hansonw** [comment]
You can leave it- I'll close this it's fixed in 1.12 :)

**Comment by imwithsam** [comment]
@hansonw I checked this again with Atom 1.12.0-beta7 and Nulcide 0.180.0 and the problem is still persisting

**Comment by hansonw** [comment]
Can you look at your logs again? We've added new prebuilt native modules for MacOS so it should be fine..

**Comment by K-Leon** [comment]
I'm experiencing same issue with MacOS Sierra, latest nuclide and Atom 1.12.1 - Nothing spectacular is in the logs. Just some Flow stuff.

**Comment by hansonw** [comment]
@imwithsam One thing that I noticed with your repo is that it doesn't have a `.gitignore`, so the file indexer is indexing everything in `node_modules` (this contains 25K+ files, which shouldn't be a problem, but maybe your system is having trouble with it). Atom's source control functionality will also be bogged down by having 25K untracked files. Try adding `node_modules` to your `.gitignore` and see if that helps.

**Comment by hansonw** [comment]
@K-Leon is this remotely or locally? If you are connecting to a remote project check the server logs as well.

**Comment by K-Leon** [comment]
@hansonw It's locally - in every project i'm opening. (.gitignore is always set)

**Comment by K-Leon** [comment]
One interesting Fact: The native Filesearch from Atom isn't affected ( cmd CMD + P ). Only Omni Search is broken.

**Comment by johnryan** [comment]
Seeing the same issue on Sierra, indexing never finishes and OmniSearch doesn't work. @K-Leon did you find a fix?

**Comment by K-Leon** [comment]
Nope - couldn't find the reason for it.

**Comment by hansonw** [comment]
@johnryan could you have a look at your logs as well? should be `$TMPDIR/nuclide-$USER-logs/nuclide.log`. Look for any messages with the word "fuzzy".

Also, while the spinner is going, could you open the Nuclide Health pane (you can find it in our toolbar, menu bar, or cmd-shift-p) and attach a screenshot of the process tree? Thanks

**Comment by johnryan** [comment]
@hansonw nothing interesting in the logs on startup i just see
```nuclide - Created new remote atom config at /var/folders/g0/_1vddtp50g1_kxl4gg8tlf280000gn/T/.nuclide/command-server/0 for port 60653 family IPv4```

Here are screenshots:

<img width="1152" alt="screen shot 2016-11-18 at 2 08 22 pm" src="https://cloud.githubusercontent.com/assets/416564/20442889/859760e0-ad98-11e6-83bf-c54de451b877.png">

<img width="1143" alt="screen shot 2016-11-18 at 2 08 30 pm" src="https://cloud.githubusercontent.com/assets/416564/20442892/89216c60-ad98-11e6-822b-8149670f0eac.png">


Let me know if I can provide any more info. Thanks!

**Comment by hansonw** [comment]
@johnryan thanks! weird that nothing from the file searcher seems to be present... could you also check the JS console when the "File search indexing" spinner is going maybe?

**Comment by johnryan** [comment]
@hansonw how do you check the JS console? Sorry i'm not too familiar with debugging this stuff.

**Comment by hansonw** [comment]
Open the devtools via cmd-option-I (same as Chrome)

**Comment by johnryan** [comment]
Interesting, there's this error:

```
TASK(17633): module.js:457
    throw err;
    ^

Error: Cannot find module 'babel-plugin-transform-decorators-legacy'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (/Users/johnryan/.atom/packages/nuclide/pkg/nuclide-node-transpiler/lib/NodeTranspiler.js:52:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

```

**Comment by hansonw** [comment]
@johnryan: Amazing! that's exactly it, I think.
@zertosh Do you know why this would be failing in the open source build? (it's from `nuclide-task` which I think you modified to require the transpiler via `--transpiler`)

**Comment by hansonw** [comment]
@johnryan after some digging, we realized that codepath would be getting triggered if you have the `babel-core` package installed somewhere globally (e.g. `~/node_modules` or `~/.node_modules`. If you don't need them, a simple workaround for now would be to delete `babel-core` from there. Not sure if that's true for @K-Leon or @imwithsam as well?

**Comment by johnryan** [comment]
@hansonw That seemed to fix it thanks! not sure why that was installed globally, possible it came when i installed flow globally.

**Comment by imwithsam** [comment]
@hansonw Sorry, just now catching up with this thread. `node_modules` is in my global .gitignore. I do not have `babel-core` installed globally. My nuclide.log now just contains:

```
2016-11-22 09:16:20.754 DEBUG (pid:5221) nuclide - Created new remote atom config at /var/folders/1t/ry79x2ln1jnd2lm2jc8vktb40000gp/T/.nuclide/command-server/0 for port 50466 family IPv4
2016-11-22 09:29:03.082 DEBUG (pid:11771) nuclide - Created new remote atom config at /var/folders/1t/ry79x2ln1jnd2lm2jc8vktb40000gp/T/.nuclide/command-server/0 for port 50655 family IPv4
```

**Comment by hansonw** [comment]
@imwithsam can you check your JS console as well when the indexing spinner is going? cmd-opt-i on Mac OS. Thanks!

**Comment by imwithsam** [comment]
@hansonw Oh yeah, I did, and there were no errors in the console
