### ISSUE TITLE
Debugger with RN 0.37: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gutenye** [facebook/nuclide#883]
### Issue and Steps to Reproduce

![screen shot 2016-11-14 at 11 58 07 am](https://cloud.githubusercontent.com/assets/377544/20252940/c1030222-aa61-11e6-911d-07438d8ff967.png)

1. use RN 0.35, the debugger works file
2. upgrade to RN 0.37, run the app, got Maximum call stack size exceeded
3. RN 0.37: use chrome debugger, works fine

### Expected Behavior

The debugger works

### Actual Behavior

Got Maximum call stack size exceeded

### Versions
* Atom: 1.12.2
* Nuclide: master branch
* Client OS: macOS 10.12.1
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by antgly** [comment]
I'm having the same issue as well. Same configuration here: Atom 1.12.3 - macOS 10.12.1

**Comment by CarvineJimmy** [comment]
This problem has been solved and I think it should be included in the next release.

https://github.com/facebook/nuclide/pull/865

**Comment by stockninja** [comment]
I'm still experiencing this bug using Nuclide 0.183.0 -- which includes #865 https://github.com/facebook/nuclide/commits/v0.183.0?after=OJ1GPQb9v8ts4fX7ceH7WXqWgW0rMzQ%3D

Atom 1.12.4, Nuclide 0.183.0, MacOS 10.11.6

**Comment by Marco62** [comment]
I'm using nuclide 0.184.0 and I have the same problem.

**Comment by mithunm93** [comment]
I'm having the same issue

```
$ apm -v
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.9.3
```

**Comment by nnquy** [comment]
I'm having the same issue

**Comment by tsaiDavid** [comment]
Just FYI, I'm having the same problem. 

```
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.8.2
```

**Comment by darrenwu** [comment]
any update, i'm useing Nuclide 0.1940 still has this proble.

apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.9.3

react-native-cli: 2.0.1
react-native: 0.39.2

**Comment by johnislarry** [comment]
Sorry I missed this, there is a fix in React Native master.  See my comments in this issue: https://github.com/facebook/nuclide/issues/900

Closing this as duplicate.
